# Generated by Django 4.0.3 on 2022-04-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0005_alter_publicacion_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=150)),
                ('receptor', models.IntegerField()),
                ('emisor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.perfil')),
            ],
        ),
    ]
