# Generated by Django 4.0.3 on 2022-03-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='presentacion',
            field=models.CharField(default=None, max_length=75, null=True),
        ),
    ]
